### PR TITLE
Addressing some Lua Issues

### LINKED ISSUE #3901: Various LUA errors
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/a157563af2005c7a777439586726dada159b60d4

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
```
[27/May] [03:27:16][1;31m[Error][0m luautils::onRegionEnter: scripts/zones/Promyvion-Holla/Zone.lua:151: attempt to index a nil value
[27/May] [03:27:23][1;31m[Error][0m luautils::onMobDeath: scripts/zones/Promyvion-Holla/mobs/Memory_Receptacle.lua:154: attempt to index a nil value
```
```
[0m[30/May] [08:39:57][1;31m[Error][0m luautils::onRegionEnter: scripts/zones/Attohwa_Chasm/Zone.lua:93: attempt to index a nil value
[30/May] [08:39:57][1;31m[Error][0m luautils::onRegionEnter: scripts/zones/Attohwa_Chasm/Zone.lua:93: attempt to index a nil value
```
```
[01/Jun] [04:37:57][1;31m[Error][0m luautils::onTrigger: .\scripts/globals/bcnm.lua:95: attempt to index local 'trade' (a nil value)
[01/Jun] [04:38:08][1;31m[Error][0m luautils::onTrigger: .\scripts/globals/bcnm.lua:95: attempt to index local 'trade' (a nil value)
```
```
[05/Jun] [14:44:20][Error] luautils::onEventFinish .\scripts/globals/crafting.lua:278: attempt to index local 'i' (a nil value)
```

### PR DESCRIPTION
**Pull request by ShelbyZ**
- bcnm.lua - accessing trade container when nil (might not be needed)
- crafting.lua - when talking with guild representative and choosing to
exit the conversation it will send a category 0 but with the exit id
(1073741824) and we were trying to handle it like an HQ crystal purchase
- Attohwa Chasm - Gasponia offset shift and caused issues with
displaying the poison
- Promy-Holla - Id's for teleporters near Memory Reps shifted and needed
adjustment
- Fixes #3901

### CODE REVIEW

File: scripts/zones/Attohwa_Chasm/Zone.lua [hunk 1]
```diff
@@ -80,16 +80,16 @@ end;
...
 function onRegionEnter(player,region)
-    local Gasponia_Offset = 16806299;
+    local Gasponia_Offset = 16806327;
 
     if (region:GetRegionID() <= 30) then
     -- TODO: Gasponia's shouldn't "always" poison you. However, in retail regions constantly reapply themselves without having to re-enter the region. In DSP that doesn't happen so I'm leaving it as-is for now.
         for i = 0, 30, 1 do
             if (region:GetRegionID() == i) then
-            local Gasponia_Offset = Gasponia_Offset + (i -1);
+                local Gasponia_Offset = Gasponia_Offset + (i -1);
```
Comment (TeoTwawki) [inline scripts/zones/Attohwa_Chasm/Zone.lua]: and ya even fixed the indent! ❤️ 

but am I seeing things or did the same var get local tagged twice in the same scope here?

**Comment by ShelbyZ** [comment]
I didn't notice that until now, it's **extra** local.

**Comment by TeoTwawki** [comment]
I already merged but I'll check further into that nil trade tomorrow. That really ought to be *impossible* so that check should never even be hit. I'm probably going to try and print some useful information to see where that coming from rather than have the function nope on outa there.
