### PR TITLE
Fixed #1116 by updating the Dismiss ability to reset the Call Wyvern abi...

### LINKED ISSUE #1116: Dragoon Dismiss Pet Cooldown Not Reset
Courtesy of @joncloud

Steps to Reproduce
------------------
1. Call Wyvern.
2. Let the Wyvern take some damage.
3. Use Spirit Link to restore the Wyvern's HP to 100%.
4. Dismiss Wyvern.

Expected Results
----------------
Wyvern is dismissed.
Call Wyvern timer is reset.

Actual Results
--------------
Wyvern is dismissed.
Call Wyvern timer is _not_ reset.

### PR DESCRIPTION
**Pull request by joncloud**
...lity's recast when HP is 100% or greater.

### CODE REVIEW

File: scripts/globals/abilities/dismiss.lua [hunk 1]
```diff
@@ -9,10 +9,16 @@ require("scripts/globals/status");
...
-	return 0,0;
-end;
-
+function onAbilityCheck(player,target,ability)
+	return 0,0;
+end;
+
 function onUseAbility(player, target, ability)
+	-- Reset the Call Wyvern Ability.
+	pet = player:getPet();
```
Comment (teschnei) [inline scripts/globals/abilities/dismiss.lua]: local pet

File: scripts/globals/abilities/dismiss.lua [hunk 2]
```diff
@@ -9,10 +9,16 @@ require("scripts/globals/status");
...
+	if pet:getHP() >= pet:getMaxHP()
```
Comment (teschnei) [inline scripts/globals/abilities/dismiss.lua]: probably want ==? when is a pets health going to be more than its max health?

File: scripts/globals/abilities/dismiss.lua [hunk 3]
```diff
@@ -9,10 +9,16 @@ require("scripts/globals/status");
...
+	then
```
Comment (teschnei) [inline scripts/globals/abilities/dismiss.lua]: put that on the previous line
