### PR TITLE
Chigoe Fix by @SOULF1RE Fix #2807

### LINKED ISSUE #2807: Chigoes remain untargetable after they aggro
Client Version (type /ver in game) :
30160203_0

Server Version (type @revision in game) :
3a852af

Source Branch (master/stable) :
master

Additional Information (Steps to reproduce/Expected behavior) :
So all you can do is just die to them. Pretty sure they're supposed to become untargetable after they deaggro though.

### PR DESCRIPTION
**Pull request by lichtl**
This is the chigoe fix by @S0ULF1RE

### CODE REVIEW

**Comment by teschnei** [comment]
do this instead:
https://github.com/DarkstarProject/darkstar/blob/master/scripts/mixins/families/phuabo.lua
https://github.com/DarkstarProject/darkstar/blob/9e96c421f3260b81e701c780c9353be6d007e9c7/scripts/zones/AlTaieu/mobs/Ul_phuabo.lua

**Comment by lichtl** [comment]
changed to mixins

File: scripts/mixins/families/chigoe.lua [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+require("scripts/globals/mixins")
+
+g_mixins = g_mixins or {}
+g_mixins.families = g_mixins.families or {}
+
+g_mixins.families.chigoe = function(mob)
+    mob:addListener("SPAWN", "CHIGOE_SPAWN", function(mob)
+        mob:hideName(true);
+        mob:untargetable(true);
+        mob:wait(2000);
```
Comment (teschnei) [inline scripts/mixins/families/chigoe.lua]: remove the wait on the three functions (its only there on sea mobs because they change subanimation and don't move while doing it)

**Comment by teschnei** [comment]
other than the wait, it looks great

**Comment by lichtl** [comment]
Ok. Wait has been removed.

**Comment by bendangelo** [comment]
Thanks for contributing :heart:
