### PR TITLE
Core: Remove Detectable Effects 

### LINKED ISSUE #2806: Sneak is not removed when attacked by a mob
Client Version (type /ver in game) :
30160203_0

Server Version (type @revision in game) :
3a852af

Source Branch (master/stable) :
master

Additional Information (Steps to reproduce/Expected behavior) :
Should be removed by any action a mob takes on the player, or any time a player takes an action on a mob.

### PR DESCRIPTION
**Pull request by MalRD**
Resolve #2806 by removing detectable effects in OnCastFinished and OnAttack.

### CODE REVIEW

File: src/map/entities/battleentity.cpp [hunk 1]
```diff
@@ -1263,6 +1263,14 @@ void CBattleEntity::OnCastFinished(CMagicState& state, action_t& action)
         }
     }
 
+    if (this != PActionTarget && PActionTarget->objtype == TYPE_PC
```
Comment (teschnei) [inline src/map/entities/battleentity.cpp]: just check if their allegiances are not the same, and you can skip the isbuff/isheal/isna, I think

**Comment by Hozu** [comment]
Should any status with EFFECTFLAG_ATTACK be removed as well in those same checks?

**Comment by teschnei** [comment]
depends if attack is on receiving an attack or an outgoing attack
