### PR TITLE
Moved some status effect deletion logic around

### LINKED ISSUE #4324: Server crashes when attempting to rest while sublimation charging
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** a72563e

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Changed Job to Scholar lvl 50
2. Activated Sublimation
3. Rested while HP draining
That got me a crash 3 times in a row. It said "DSGame-server.exe has stopped working" so I think that's actually a crash. Not a debug break or anything.

### PR DESCRIPTION
**Pull request by teschnei**
RemovedStatusEffect only flags for deletion
New function DeleteStatusEffects actually does the deletion

Can no longer accidentally run into undefined behaviour when deleting an effect
inside OnEffectTick

Fixes #4324 

Additional information:

This technically hasn't always been an issue - must have come about when I moved some effect stuff around.  However, I think that prior to that, it was still undefined behaviour (or wrong behaviour) rather than being a crash.  If I had to guess, some effects ticks would randomly get skipped instead.  So when I changed the effect container, it just made the bug more obvious.

Also, this has a side effect of only sending the effect updating packets once per tick instead of a whole set for each expiring effect (if multiple effects expire on the same tick)

### CODE REVIEW

File: src/map/status_effect_container.cpp [hunk 1]
```diff
@@ -460,14 +474,31 @@ void CStatusEffectContainer::RemoveStatusEffect(uint32 id, bool silent)
...
+{
+    CStatusEffect* PStatusEffect = m_StatusEffectList.at(id);
+    PStatusEffect->deleted = true;
+    if (m_POwner->objtype == TYPE_PC)
+    {
+        CCharEntity* PChar = (CCharEntity*)m_POwner;
+
+        if (PStatusEffect->GetIcon() != 0)
+        {
+            if (silent == false)
```
Comment (takhlaq) [inline src/map/status_effect_container.cpp]: `!silent` cause fuck reading
