### PR TITLE
Fully implemented Community Service quest

### LINKED ISSUE #3714: Jeuno Community Service Quest Bugged - cService logic
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Source Branch_** (master) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The jeuno community service quest logic is incorrect. Currently you have to select light posts in order. ie: If cService == 1, cService = 2.

The quest should not care what order the lights are selected.

http://ffxiclopedia.wikia.com/wiki/Community_Service

### PR DESCRIPTION
**Pull request by wrenffxi**
Fixes #3714.

edit: added 8PM recruiting notification and number of remaining lamps notice.

### CODE REVIEW

File: scripts/zones/Lower_Jeuno/Zone.lua [hunk 1]
```diff
@@ -81,16 +84,42 @@ end;
 
 function onGameHour()
     local VanadielHour = VanadielHour();
-
+    local playerOnQuestId = GetServerVariable("[JEUNO]CommService");
```
Comment (takhlaq) [inline scripts/zones/Lower_Jeuno/Zone.lua]: can probably store this as localVar in one of the quest npc unless it needs to persist after server crash (death to all server vars)

File: scripts/zones/Lower_Jeuno/Zone.lua [hunk 2]
```diff
@@ -81,16 +84,42 @@ end;
...
+        for i=0,11 do
+            local lamp = GetNPCByID(lampIdOffset + i);
+            lamp:setAnimation(ANIMATION_CLOSE_DOOR);
+        end
 
-    elseif (VanadielHour == 5) then
+    -- 8PM: make quest available
+    elseif (VanadielHour == 20) then        
         SetServerVariable("[JEUNO]CommService",0);
+        -- TO DO: notify anyone with Lamp Lighter's Membership Card that it's time
```
Comment (takhlaq) [inline scripts/zones/Lower_Jeuno/Zone.lua]: can modify luautils::onGameHour to push zone object and then loop over all players in zone
```
local players = zone:getPlayers();
for name, player in pairs(players) do
    -- do stuff;
end
```

File: scripts/zones/Lower_Jeuno/npcs/Zauko.lua [hunk 3]
```diff
@@ -34,110 +37,115 @@ end;
...
-            if (hour >= 18 and hour < 23) then -- If Quest Repeat is accepted but lamps are not lit
-                player:startEvent(0x0077); -- Task Failed Dialogue
+            if hour >= 20 and hour < 21 then
+                player:startEvent(0x0073); -- tell player it's too early to start lighting lamps.
+            elseif allLampsLit then
+                player:startEvent(0x0075,doneCommService); -- all lamps are lit. win quest.
+            elseif hour >= 21 or hour < 1 then
+                player:startEvent(0x0072); -- tell player they can start lighting lamps.
+            else
+                SetServerVariable("[JEUNO]CommService",-1); -- frees player from quest, but don't allow anyone else to take it today.
```
Comment (takhlaq) [inline scripts/zones/Lower_Jeuno/npcs/Zauko.lua]: localVar here too

File: scripts/zones/Lower_Jeuno/npcs/Vhana_Ehgaklywha.lua [hunk 4]
```diff
@@ -1,116 +1,81 @@
...
+end;
 
 -----------------------------------
 -- onTrigger Action
 -----------------------------------
+
 function onTrigger(player,npc)
-    player:showText(npc, 7160);
-end; 
+    -- speaking to pathing NPCs stops their progress, and they never resume
```
Comment (takhlaq) [inline scripts/zones/Lower_Jeuno/npcs/Vhana_Ehgaklywha.lua]: hmm that shouldnt happen unless npc:wait(-1) (which it shouldnt ever be -1 unless the npc absolutely has to stay frozen forever until something tells it to resume pathing)

File: scripts/zones/Lower_Jeuno/Zone.lua (hunk 1 above)
Comment (wrenffxi) [inline scripts/zones/Lower_Jeuno/Zone.lua]: I think it does need to persist across server crash.  Otherwise you could get two players flagged for the quest on the same game-day.

Comment (takhlaq) [inline scripts/zones/Lower_Jeuno/Zone.lua]: o ya
derp

disregard my other comments though i'd prefer the players in zone notified to light lamps before merging

Comment (wrenffxi) [inline scripts/zones/Lower_Jeuno/Zone.lua]: Understood.  Will get that in shortly.  Thanks!

**Comment by wrenffxi** [comment]
Added 8pm recruiting notice for anyone in zone with membership card.
Added notice for number of remaining lamps.

**Comment by takhlaq** [comment]
looks good, thanks!
